services:
    Locastic\ActivityLogs\Command\PopulateCurrentDataTrackersCommand:
        autowire: true
        tags: ['console.command']

    Locastic\ActivityLogs\Command\CreateLoggableIndexesCommand:
        autowire: true
        tags: ['console.command']
