services:
    locastic_activity_log.metadata.loggable.context_collection_factory.cached:
        class: Locastic\ActivityLog\Metadata\LoggableContext\Factory\CachedLoggableContextCollectionFactory
        decorates: 'locastic_activity_log.metadata.loggable.context_collection_factory'
        decoration_priority: -10
        arguments:
            - '@.inner'
            - '@api_platform.cache.metadata.property.legacy'

#   XML is the default
    locastic_activity_log.metadata.loggable.context_collection_factory:
        alias: locastic_activity_log.metadata.loggable.context_collection_factory.xml

    locastic_activity_log.metadata.loggable.context_collection_factory.xml:
        class: Locastic\ActivityLog\Metadata\LoggableContext\Factory\ExtractorLoggableContextCollectionFactory
        arguments:
            - '@locastic_activity_logs.metadata.loggable_class_extractor.xml'

    Locastic\ActivityLog\Metadata\LoggableContext\Factory\LoggableContextCollectionFactoryInterface:
        alias: 'locastic_activity_log.metadata.loggable.context_collection_factory'

    locastic_activity_log.metadata.loggable.context_collection_factory.yaml:
        class: Locastic\ActivityLog\Metadata\LoggableContext\Factory\ExtractorLoggableContextCollectionFactory
        decorates: 'locastic_activity_log.metadata.loggable.context_collection_factory'
        arguments:
            - '@locastic_activity_logs.metadata.loggable_class_extractor.yaml'
            - '@.inner'

    locastic_activity_log.metadata.loggable.context_collection_factory.attribute:
        class: Locastic\ActivityLog\Metadata\LoggableContext\Factory\AttributeLoggableContextCollectionFactory
        decorates: 'locastic_activity_log.metadata.loggable.context_collection_factory'
        arguments:
            - '@.inner'
            - '%locastic_activity_log.dir.loggable_classes%'

    Locastic\ActivityLog\Metadata\LoggableContext\Factory\LoggableContextFactoryInterface:
        alias: 'locastic_activity_log.metadata.loggable.context_factory'

#    locastic_activity_log.metadata.loggable.context_factory:
#        class: Locastic\ActivityLog\Metadata\LoggableContext\Factory\LoggableContextFactory
#        autowire: true
