services:
    Locastic\Loggastic\Identifier\LogIdentifierExtractorInterface:
        alias: 'Locastic\Loggastic\Identifier\LogIdentifierExtractor'

    Locastic\Loggastic\Identifier\LogIdentifierExtractor:
        autowire: true
