services:
    Locastic\Loggastic\EventListener\SendActivityLogMessageToTransportListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Messenger\Event\SendMessageToTransportsEvent }

    Locastic\Loggastic\EventListener\SendUpdateActivityLogMessageToTransportListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Messenger\Event\SendMessageToTransportsEvent }
