services:
    Locastic\Loggastic\Metadata\Extractor\YamlLoggableExtractor:
        arguments:
            - type: collection

    Locastic\Loggastic\Metadata\Extractor\XmlLoggableExtractor:
        arguments:
            -   type: collection
