services:
    Locastic\Loggastic\EventSubscriber\ActivityLogDoctrineSubscriber:
        autowire: true
        tags:
            - { name: 'doctrine.event_listener', event: 'preRemove' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'postRemove' }
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'postFlush' }
